# Generated by Django 6.0.7 on 2026-07-27 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gremios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Objetivo')),
                ('race_class', models.CharField(max_length=100, verbose_name='Raza/Clase (Job Title)')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('threat_level', models.IntegerField(default=10, verbose_name='Nivel de Amenaza (Confidence %)')),
                ('estimated_reward', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Recompensa (Contract Value)')),
                ('days_in_funnel', models.IntegerField(default=0, verbose_name='Días de Rastreo')),
                ('emails_sent', models.IntegerField(default=0, verbose_name='Cuervos Enviados (Emails)')),
                ('calls_made', models.IntegerField(default=0, verbose_name='Ataques Físicos (Llamadas)')),
                ('status', models.CharField(choices=[('AVISTAMIENTO', 'Avistamiento (Nuevo Lead)'), ('INVESTIGACION', 'Investigación (Calificando)'), ('EMBOSCADA', 'Emboscada (Propuesta)'), ('COMBATE', 'En Combate (Negociación)'), ('ABATIDO', 'Abatido (Ganado/Closed Won)'), ('ESCAPO', 'Escapó (Perdido/Closed Lost)')], default='AVISTAMIENTO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_hunter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunted_leads', to=settings.AUTH_USER_MODEL)),
                ('gremio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='gremios.gremio')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('potential_reward', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('TABERNA', 'Taberna (Nuevo)'), ('EXPLORACION', 'Exploracion (En Proceso)'), ('COMBATE', 'Combate (Negociacion)'), ('TESORO', 'Tesoro (Cerrado o Ganado)'), ('CEMENTERIO', 'Cementerio (Cerrado Perdido)')], default='TABERNA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to=settings.AUTH_USER_MODEL)),
                ('gremio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='gremios.gremio')),
            ],
        ),
    ]
